zimzim_worldcup_game:
    pattern:  /
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Game:index" }

zimzim_worldcup_game_show:
    pattern:  /{id}/show
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Game:show" }

zimzim_worldcup_game_new:
    pattern:  /new
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Game:new" }

zimzim_worldcup_game_create:
    pattern:  /create
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Game:create" }
    requirements: { _method: post }

zimzim_worldcup_game_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Game:edit" }

zimzim_worldcup_game_update:
    pattern:  /{id}/update
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Game:update" }
    requirements: { _method: post|put }

zimzim_worldcup_game_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Game:delete" }
    requirements: { _method: post|delete }

zimzim_worldcup_game_editscore:
    pattern:  /{id}/editscore
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Game:editscore" }

zimzim_worldcup_game_updatescore:
    pattern:  /{id}/updatescore
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Game:updatescore" }
    requirements: { _method: post|put }

zimzim_worldcup_game_nextgame:
    pattern:  /nextgame/
    defaults: { _controller: "ZIMZIMBundlesWorldCupBundle:Game:nextgame" }
    requirements: { _method: get }